export const CHANGE_TOP_BANNER = 'recommend/CHANGE_TOP_BANNER'
export const CHANGE_RECOMMENDS = 'recommend/CHANGE_RECOMMENDS'
export const CHANGE_ALBUM = 'recommend/CHANGE_ALBUM'
export const CHANGE_UP_RANKING = 'recommend/CHANGE_UP_RANKING'
export const CHANGE_NEW_RANKING = 'recommend/CHANGE_New_RANKING'
export const CHANGE_ORIGIN_RANKING = 'recommend/CHANGE_ORIGIN_RANKING'
